# Generated by Django 3.2.5 on 2022-06-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block29app', '0004_auto_20220605_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block29',
            name='coll_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
