# Generated by Django 3.2.5 on 2022-06-06 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block29app', '0005_alter_block29_coll_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block29',
            name='formatted',
        ),
    ]
